/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.apress.spring_quick.autoconfig;

public class Library {

    public boolean someLibraryMethod() {
        return true;
    }

}
