/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.apress.spring_quick.reactor;

import reactor.core.publisher.Mono;

import java.time.Duration;
import java.time.temporal.ChronoUnit;

public class App {

    public String getGreeting() {
        return Mono.just("Hello world.")
                .retry(2)
                .block(Duration.of(1, ChronoUnit.SECONDS));
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
