CREATE TABLE IF NOT EXISTS category (id INTEGER IDENTITY PRIMARY KEY, name VARCHAR(100), description VARCHAR(2000), age_group VARCHAR(20), created DATETIME, inserted BIGINT);

CREATE TABLE IF NOT EXISTS channel (id INTEGER, name VARCHAR(100), min_Age INTEGER, max_Age INTEGER);
CREATE TABLE IF NOT EXISTS messages (message_id INTEGER, author VARCHAR(100), text CLOB);
CREATE TABLE IF NOT EXISTS topic (name VARCHAR(100), description CLOB, channel INTEGER);
