/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.apress.spring_quick.aop;

import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.*;

@Configuration
@PropertySource("classpath:/application.properties")
@ComponentScan // <-- scan using current package as base
@EnableAspectJAutoProxy // <--- AOP
public class App {

    public static void main(String[] args) {
        final ApplicationContext applicationContext = new AnnotationConfigApplicationContext(App.class);

        Repository repository = applicationContext.getBean(Repository.class);
        Iterable<Object> all = repository.findAll();
        all.forEach(System.out::println);

        repository.delete("123");
    }
}
